### ISSUE TITLE
svg not working

### ISSUE THREAD

**Issue by enric1994** [natar-io/Papart-examples#1]
Hi, I follow the wiki and I generate this svg.
[marker1.svg.tar.gz](https://github.com/poqudrof/Papart-examples/files/560462/marker1.svg.tar.gz)
I am trying to use it in the planetes example but I fail. How I can use this single marker in the class Earth?
Thanks

**Comment by poqudrof** [comment]
The svg seems good, I will try it next time I plug my printer.

**Comment by poqudrof** [comment]
It works for me, here is the code: 
http://jiii.fr/tmp/test-marker.7z

I just printed the SVG from Inkscape on a paper of size A4.

**Comment by poqudrof** [comment]
Did you try again ?   If you have suggestions to improve the  "make your markerboard" wiki page please explain what is not clear/missing 
  https://github.com/poqudrof/Papart-examples/wiki/markerboard

**Comment by enric1994** [comment]
I leave the project a month ago sorry.
Thanks for your help.

**Comment by poqudrof** [comment]
No problem you are welcome :)
