### ISSUE TITLE
the import of org.bytedeco cannot be resolved

### ISSUE THREAD

**Issue by kweimingxx** [natar-io/Papart-examples#4]
I got this message when I use the library
I'm running this library on MacOS 
does it work fine on Mac?

**Comment by poqudrof** [comment]
Hello, I did ont make a Mac OS binary for JavaCV yet. It should work fine, try to download JavaCV 1.3 from the bydeco website. 
I will make a binary for osx soon. 
Cheers, 
Jérémy

**Comment by poqudrof** [comment]
You may have dependency problem for OpenCV (called by JavaCV): 

So, in windows you will need `msvcr120` to be installed. I asked google, and it seems to be available here: https://www.microsoft.com/en-us/download/details.aspx?id=40784 . 
Check if the files exists after install. I recommend to install both x86 and x64. 

From [javacpp-preset OpenCV](https://github.com/bytedeco/javacpp-presets/blob/master/opencv/src/main/java/org/bytedeco/javacpp/presets/opencv_core.java) 
``` java 
    @Platform(value = "windows", define = "_WIN32_WINNT 0x0502", link =  {"opencv_core310", "opencv_imgproc310"}, preload = {"msvcr120", "msvcp120"}),
    @Platform(value = "windows-x86", preloadpath = "C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/redist/x86/Microsoft.VC120.CRT/"),
    @Platform(value = "windows-x86_64", preloadpath = "C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/redist/x64/Microsoft.VC120.CRT/")},
        target = "org.bytedeco.javacpp.opencv_core", helper = "org.bytedeco.javacpp.helper.opencv_core")
```

I cannot try the OSX binary, as I don't have a mac.

**Comment by poqudrof** [comment]
It works on OSX, with the "Processing" video input. 
It seems that we forgot to add this line in some examples:   
``` java 
import processing.video*; 
``` 

Try to add it and it will work !
