### ISSUE TITLE
Calibration Real Sense

### ISSUE THREAD

**Issue by jalbouys** [natar-io/Papart-examples#9]
Je n'arrive actuellement pas à calibrer la RealSense avec la nouvelle version de PapARt. Cette dernière fonctionne bien quand je lance l'application DepthVisualization. Mais q avec touchCalibration impossible de voir la détection des mes doigts (même en montant ou en baissant le plan avec les boutons associés"

**Comment by poqudrof** [comment]
Je crois que le plan est très en-dessous de la table avec la calibration par défaut. Tu as essayé de le monter de 15 ou 20 mm  ? 
Est-ce que le touch 3D affiche quelque chose ?

**Comment by jalbouys** [comment]
Je viens d'essayer en montant le plan mais toujours aucune détection. Par Touch 3D tu parles d'un programme contenue dans le dépôt PapARt-example ? Sinon non le touch 3D sur la calibration du plan (ou dans d'autres programme) ne m'affiche strictement rien.

**Comment by poqudrof** [comment]
Je veux dire dans  `TouchCalibration`: il y a un bouton pour gérer la calibration 3D en bas à gauche avec le bouton pour sauver. 
Si la calibration à l'air bonne après l'étape de calibration le plan doit être bon aussi. Quand je parle 15 ou 20 mm c'est appuyer 15 ou 20 ou 40 fois sur le bouton `planeUp`. La vitesse du `planeUp` est réglée par le `planeUpAmount` et c'est en millimètres. 

Si c'est toujours pas bon envoie-moi le contenu de  `sketchbook/libraries/PapARt/data/calibration/PlaneProjectionCalibration.xml`. Pour référence ma dernière calibration avec le hardware que je vous livré c'est ça: 

``` xml 

<Calibration>
  <Plane>
    <Position x="-69.21979" y="95.23865" z="658.8329"/>
    <Normal x="-0.05759317" y="0.49255124" z="0.86837566"/>
    <Height Height="15.0"/>
  </Plane>
  <Homography m00="-1.1391184" m01="0.3585522" m02="0.44701427" m03="0.0" m10="-0.03805845" m11="-1.5349373" m12="0.82887393" m13="0.0" m20="-0.08640442" m21="0.71500325" m22="1.0" m23="0.0" m30="0.0" m31="0.0" m32="0.0" m33="1.0"/>
</Calibration>

```
